### ISSUE TITLE
Is the code F/OSS?

### ISSUE THREAD

**Issue by BK-Teal** [dzhavat/dzhavat.github.io#5]
I would like to fork your blog's CSS and use it for my own (only if that's okay by you, of course!), but I don't see a F/OSS license on this repo. Is that intentional?

**Comment by dzhavat** [comment]
No, it's not intentional. I've forgotten to add a license. Thanks for pointing that out. Will add one soon :)

Anyway, feel free to reuse the CSS however you want.
